name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Gera uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração da Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Rayan-Novik
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do resultado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "atualiza animação snake 🐍"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Push para o branch atual
        run: git push

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
